"""
Django settings for simple_django_keycloak_auth project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-_+j*9h!uo6%@s0yj200l+1a4c36hn_$o5)-!m-^y8wot8r25j8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

AUTHENTICATION_BACKENDS = (
    'django_keycloak_auth.auth.KeycloakAuth',
    'django.contrib.auth.backends.ModelBackend'
)



REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'django_keycloak_auth.drf_auth.CustomOIDCAuthentication',
    ],
     'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
    )
}
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "django_keycloak_auth",
    "users"
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_keycloak_auth.auth_middleware.KeycloakMiddleware'
]

ROOT_URLCONF = 'simple_django_keycloak_auth.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'simple_django_keycloak_auth.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

KEYCLOAK_AUTH_CONFIG = {
    "OIDC_RP_CLIENT_ID": "Journeypal",
    "OIDC_RP_CLIENT_SECRET": "Mrji0Tbf2wVoxLBDOVgy32jaq5RocBeU",
    "OICD_REALM": "nextweekwithus-test",
    "OICD_HOST": "https://auth.hastsolutions.com",
    "USER_PROFILE_MODEL": None,
    "OIDC_STORE_ACCESS_TOKEN": True,
    "OIDC_STORE_REFRESH_TOKEN": True,
    "KEYCLOAK_CAST_ATTRIBUTES": [
        'django_keycloak_auth.cast_attributes.CastDateKeycloakAttribute'
    ],
    "KEYCLOAK_ATTRIBUTES_MAPPER": {
        "username": "username",
        "email": "email",
        "last_name": "lastName",
        "first_name": "firstName",
        "report_count": "reportCount",
        "journey_groups": "journeyGroups",
        "is_blocked": "isBlocked",
        "is_freezed": "isFreezed",
        "age_limitation_accepted": "ageLimitationAccepted",
        "accepted_terms_and_condition":  "termsAndConditionAccepted",
        "gender": "gender",
        "date_type": "dateType",
        "birthdate": "birthdate",
        "website": "website",
        "locale": "locale",
        "user_rate": "userRate",
        "followers": "followers",
        "job": "job",
        "region": "region",
        "city": "city",
        "country": "country",
        "zoneinfo": "zoneInfo",
        "nickname": "middleName",
        "job_title": "jobTitle",
        "description": "description",
        "address": "address",
        "phone_number": "phoneNumber",
        "is_attendee_visible": "isAttendeeVisible",
        "is_groups_visible": "isGroupsVisible",
        "is_last_seen_visible": "isLastSeenVisible",
        "is_phone_number_verified": "isPhoneVerified",
        "is_phone_number_public": "isPhonePublic",
        "is_email_verified": "isEmailVerified",
        "is_email_public": "isEmailPublic",
        "is_user_verified": "isUserVerified"
    }
}

LOGIN_REDIRECT_URL = '/'  # after login
LOGOUT_REDIRECT_URL = '/'  # after logout
AUTH_USER_MODEL = 'users.CustomUser'
STATIC_URL = 'static/'
